version: '3.7'

services:
  test-h2-db:
    image: oscarfonts/h2:latest
    container_name: h2-test
    restart: always
    ports:
      - "1521:1521"
      - "10081:10081"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./data/db:/data/db
  dev-mysql-db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d