spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: bGV3aXMxMjMyMTNmZHNrbGpmYXNka2wxMjMzMTIyMTMyMTM5MDg0MzE5MDQyMTgwOWZkc2tsYWpmc2FkbGt3ZXFybGo= # lewis123213fdskljfasdkl12331221321390843190421809fdsklajfsadlkweqrlj
  access-token-validity-in-seconds: 600 # 10 min