spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: bGV3aXMxMjMyMTNmZHNrbGpmYXNka2wxMjMzMTIyMTMyMTM5MDg0MzE5MDQyMTgwOWZkc2tsYWpmc2FkbGt3ZXFybGo= # lewis123213fdskljfasdkl12331221321390843190421809fdsklajfsadlkweqrlj
  access-token-validity-in-seconds: 600 # 10 min

server:
  port: 8081